name: Backend Flow

on: [push]

jobs:
  test:
    name: test and build
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      
      - name: Setup AllowAnyOrigin
        run: |
          sed -i 's/{AllowAnyOrigin}/true/g' StaffManagement.Service/appsettings.json

      - name: Test appp 
        run: |
          cd StaffManagement.Tests
          dotnet test
    
  deploy-image:
    name: Deploy image to Github Container Registry
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      
      - name: set lower case owner name
        run: |
          echo "OWNER_LC=${OWNER,,}" >>${GITHUB_ENV}
        env:
          OWNER: '${{ github.repository_owner }}'

      - name: Build and push
        run: |
          docker build . -t ghcr.io/${{ env.OWNER_LC }}/${{ github.repository }}:latest
          docker push ghcr.io/${{ env.OWNER_LC }}/${{ github.repository }} :latest
